"""Generate documentation only. Never connects to a database or executes SQL."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
T=[]
def add(name,phase,grain,fields,keys='',rules='',mode='mutable',global_=False):
    cols=[dict(name='id',type='uuid',nullable=False,reference=None)]
    if not global_ and name!='org.companies': cols.append(dict(name='company_id',type='uuid',nullable=False,reference='org.companies.id'))
    for spec in fields.split(';'):
        if not spec.strip():continue
        pair=spec.strip().split('=',1); left=pair[0].split(':',1)
        field,typ=left[0],left[1]; nullable=typ.endswith('?');typ=typ.rstrip('?')
        cols.append(dict(name=field,type=typ,nullable=nullable,reference=pair[1] if len(pair)>1 else None))
    cols.append(dict(name='created_at',type='timestamptz',nullable=False,reference=None))
    if mode=='mutable':cols += [dict(name='updated_at',type='timestamptz',nullable=False,reference=None),dict(name='version',type='integer',nullable=False,reference=None)]
    T.append(dict(name=name,phase=phase,grain=grain,mode=mode,columns=cols,keys=keys,rules=(rules or 'ใช้กฎ tenant, FK และ audit กลาง') + ('; structured Thai address: composite geography FKs + postal mapping ตาม 07-address-model.md' if name in {'org.companies','org.branches','catalog.supplier_addresses'} else '')))
# Shared Thai geographical reference data. IDs are internal UUIDs, not official codes.
add('geo.provinces','F','หนึ่งจังหวัด/กรุงเทพมหานคร','official_code:text;name_th:text;name_en:text?;active:boolean;source_ref:text;source_version:text','U(official_code)','global reference; runtime read-only; รหัสทางการเป็น text แยกจาก UUID; ไม่ลบรายการที่เคยอ้างอิง',global_=True)
add('geo.districts','F','หนึ่งอำเภอ/เขต','province_id:uuid=geo.provinces.id;official_code:text;name_th:text;name_en:text?;active:boolean;source_ref:text;source_version:text','U(official_code); U(province_id,id)','global reference; parent geography ห้ามเปลี่ยนเมื่อใช้งานแล้ว ให้สร้าง record ใหม่และ retire record เดิม',global_=True)
add('geo.subdistricts','F','หนึ่งตำบล/แขวง','district_id:uuid=geo.districts.id;official_code:text;name_th:text;name_en:text?;active:boolean;source_ref:text;source_version:text','U(official_code); U(district_id,id)','global reference; parent geography immutable หลังใช้งาน; ไม่ hard delete',global_=True)
add('geo.postal_codes','F','หนึ่งรหัสไปรษณีย์ไทย','code:text;active:boolean;source_ref:text;source_version:text','U(code)','CHECK code เป็นเลข 5 หลัก; เก็บ text ไม่ integer; id เป็น UUID; ไม่ใช้รหัสไปรษณีย์อนุมานจังหวัดโดยไม่มี mapping',global_=True)
add('geo.subdistrict_postal_codes','F','หนึ่งคู่ตำบลกับรหัสไปรษณีย์ที่อนุญาต','subdistrict_id:uuid=geo.subdistricts.id;postal_code_id:uuid=geo.postal_codes.id;coverage_note:text?;active:boolean;source_ref:text;source_version:text','U(subdistrict_id,postal_code_id); I(postal_code_id)','many-to-many mapping; ตรวจ coverage เพิ่มเมื่อพื้นที่ย่อยมีเงื่อนไข; ไม่ลบ mapping ที่ถูกใช้; เปลี่ยน active ผ่าน reference import เท่านั้น',global_=True)
# Shared document registry: real FK target, not a loose type/id association.
add('org.companies','F','หนึ่งบริษัท','code:text;legal_name:text;tax_id:text?;address_line1:text;address_line2:text?;province_id:uuid=geo.provinces.id;district_id:uuid=geo.districts.id;subdistrict_id:uuid=geo.subdistricts.id;postal_code_id:uuid=geo.postal_codes.id;timezone:text;base_currency:char(3);active:boolean','U(code)','สร้างสำนักงานใหญ่และคลังหลักใน transaction เดียว ห้าม hard delete บริษัทที่ provision แล้ว')
add('org.branches','F','หนึ่งสาขาในบริษัท','code:text;name:text;is_head_office:boolean;active:boolean;address_line1:text;address_line2:text?;province_id:uuid=geo.provinces.id;district_id:uuid=geo.districts.id;subdistrict_id:uuid=geo.subdistricts.id;postal_code_id:uuid=geo.postal_codes.id;contact:jsonb','U(company_id,code); partial U(company_id) WHERE is_head_office','สำนักงานใหญ่ต้อง active และเปลี่ยน identity/company/type ไม่ได้; deferred exact-one trigger ทุกบริษัท')
add('org.warehouses','F','หนึ่งคลังในสาขา','branch_id:uuid=org.branches.id;code:text;name:text;is_default:boolean;active:boolean','U(company_id,branch_id,code); partial U(company_id,branch_id) WHERE is_default','ทุกสาขาต้องมีคลังหลักหนึ่งแห่ง ลบไม่ได้ active เมื่อสาขา active')
add('org.locations','W','หนึ่งโหนดสถานที่จริง','warehouse_id:uuid=org.warehouses.id;parent_id:uuid?=org.locations.id;code:text;name:text;kind:text;is_stockable:boolean;active:boolean','U(company_id,warehouse_id,code); I(company_id,parent_id)','ZONE/COLD_ROOM/RACK/BIN/STAGING; parent warehouse เดียวกัน ห้ามวงจร; posting ใช้ stockable leaf')
add('org.usage_points','W','หนึ่งจุดใช้งาน/ครัว','branch_id:uuid=org.branches.id;code:text;name:text;active:boolean','U(company_id,branch_id,code)')
add('security.users','F','หนึ่งตัวตนผู้ใช้กลาง','username:text;email:text;password_hash:text;active:boolean;locale:text;last_login_at:timestamptz?','U(lower(username)); U(lower(email))','ไม่ hard delete; locale th/lo/zh/my; ไม่เผย hash',global_=True)
add('security.memberships','F','หนึ่งสมาชิกต่อบริษัท','user_id:uuid=security.users.id;active:boolean;joined_at:timestamptz','U(company_id,user_id)','ไม่ให้ company admin ยึด global user ที่อยู่บริษัทอื่นผ่านการเปลี่ยน email/password')
add('security.access_scopes','F','หนึ่งขอบเขตสิทธิ์','kind:text;branch_id:uuid?=org.branches.id;warehouse_id:uuid?=org.warehouses.id','U NULLS NOT DISTINCT(company_id,kind,branch_id,warehouse_id)','COMPANY: both null; BRANCH: branch only; WAREHOUSE: branch+warehouse matching')
add('security.membership_scopes','F','หนึ่งสมาชิกที่เข้าถึง scope','membership_id:uuid=security.memberships.id;scope_id:uuid=security.access_scopes.id','U(company_id,membership_id,scope_id)')
add('security.roles','F','หนึ่งบทบาทภายในบริษัท','code:text;name:text;system_managed:boolean;active:boolean','U(company_id,code)')
add('security.permissions','F','หนึ่ง permission code กลาง','code:text;module:text;description:text','U(code)','global catalog ไม่ใช่สิทธิ์ข้าม tenant',global_=True)
add('security.role_permissions','F','หนึ่ง permission ของ role','role_id:uuid=security.roles.id;permission_id:uuid=security.permissions.id','U(company_id,role_id,permission_id)')
add('security.role_assignments','F','หนึ่ง role ที่ผูก membership+scope','membership_scope_id:uuid=security.membership_scopes.id;role_id:uuid=security.roles.id;active:boolean','U(company_id,membership_scope_id,role_id)','ไม่มี tenant-wide superuser โดยปริยาย; คง admin คนสุดท้าย')
add('security.sessions','F','หนึ่งอุปกรณ์/session ของ user','user_id:uuid=security.users.id;family_id:uuid;expires_at:timestamptz;revoked_at:timestamptz?;revocation_reason:text?;device_label:text?;ip:inet?;user_agent:text?','I(user_id,revoked_at); U(family_id)','session กลาง ตรวจ membership ปัจจุบันทุกบริษัท',global_=True)
add('security.refresh_tokens','F','หนึ่งรุ่น token ใน session','session_id:uuid=security.sessions.id;jti:uuid;token_hash:text;expires_at:timestamptz;consumed_at:timestamptz?;revoked_at:timestamptz?;replaced_by_id:uuid?=security.refresh_tokens.id','U(jti); U(token_hash); I(session_id)','rotation atomic และ revoke family เมื่อ reuse; ไม่มี plaintext',global_=True)
add('platform.documents','P','หนึ่งเอกสารธุรกิจที่เป็น FK กลาง','branch_id:uuid=org.branches.id;kind:text;document_no:text?;status:text;effective_at:timestamptz?;created_by:uuid=security.users.id;confirmed_by:uuid?=security.users.id;confirmed_at:timestamptz?;reverses_document_id:uuid?=platform.documents.id','U(company_id,branch_id,kind,document_no); I(company_id,kind,status,created_at)','typed header exactly one ตาม kind; status ต้อง transition ผ่าน service; ไม่ใช้ทะเบียนนี้แทนตารางธุรกิจ')
add('platform.document_lines','P','หนึ่ง line identity ในเอกสาร','document_id:uuid=platform.documents.id;line_no:integer;kind:text','U(company_id,document_id,line_no)','มี typed child exactly one ตอน document สมบูรณ์; ID ไม่เปลี่ยนเมื่อ PO revision')
add('platform.number_sequences','P','หนึ่งเลข running ตามชนิด/สาขา/ปี','branch_id:uuid=org.branches.id;kind:text;fiscal_year:integer;prefix:text;next_value:bigint','U(company_id,branch_id,kind,fiscal_year)','atomic UPDATE RETURNING; เลขยกเลิกไม่ reuse; gaps ยอมรับได้')
add('platform.files','F','หนึ่ง object ส่วนตัว','object_key:text;original_name:text;mime_type:text;size_bytes:bigint;sha256:text;scan_status:text;uploaded_by:uuid=security.users.id;retention_until:timestamptz?;deleted_at:timestamptz?','U(company_id,object_key); I(company_id,created_at)','ไม่เก็บ signed URL เป็น canonical; FK references ก่อนลบ; scan clean ก่อนใช้งาน')
add('platform.document_files','P','หนึ่งไฟล์ประกอบเอกสาร','document_id:uuid=platform.documents.id;line_id:uuid?=platform.document_lines.id;file_id:uuid=platform.files.id;purpose:text','U NULLS NOT DISTINCT(company_id,document_id,line_id,file_id,purpose)','line ต้องอยู่ document เดียวกัน')
add('platform.approval_policies','P','หนึ่งรุ่นกฎอนุมัติ','code:text;revision:integer;scope_id:uuid=security.access_scopes.id;document_kind:text;min_amount:numeric(20,2)?;max_amount:numeric(20,2)?;currency:char(3);active:boolean;maker_checker:boolean','U(company_id,code,revision)','ไม่แก้ policy ที่ถูกใช้งาน; resolve precedence ชัด ไม่รวมกฎโดยเดา')
add('platform.approval_policy_steps','P','หนึ่งขั้นอนุมัติ','policy_id:uuid=platform.approval_policies.id;step_no:integer;role_id:uuid=security.roles.id;required_count:integer','U(company_id,policy_id,step_no)','quorum >0')
add('platform.approval_requests','P','หนึ่งคำขออนุมัติ snapshot','document_id:uuid=platform.documents.id;subject_revision:integer;policy_id:uuid=platform.approval_policies.id;policy_snapshot:jsonb;subject_hash:text;requested_by:uuid=security.users.id;status:text','I(company_id,document_id,status)','ห้ามอนุมัติรุ่นคนละ hash; company/branch/scope ต้องตรวจทุก action')
add('platform.approval_decisions','P','หนึ่งผลตัดสินใจต่อคน/ขั้น','request_id:uuid=platform.approval_requests.id;step_no:integer;decided_by:uuid=security.users.id;decision:text;reason:text?;decided_at:timestamptz','U(company_id,request_id,step_no,decided_by)','APPROVE/REJECT/RETURN; immutable',mode='append')
add('platform.setting_definitions','F','หนึ่งชนิด setting','key:text;value_schema:jsonb;default_value:jsonb;allowed_scope_kinds:jsonb;requires_approval:boolean','U(key)','versioned config schema ไม่ใช่ arbitrary executable JSON',global_=True)
add('platform.setting_versions','P','หนึ่งรุ่นค่าที่ scope','definition_id:uuid=platform.setting_definitions.id;scope_id:uuid=security.access_scopes.id;revision:integer;value:jsonb;valid_from:timestamptz;valid_to:timestamptz?;approval_document_id:uuid?=platform.documents.id;changed_by:uuid=security.users.id','U(company_id,definition_id,scope_id,revision); no overlapping active periods','warehouse > branch > company > default; transaction snapshot effective settings')
add('platform.ui_features','F','หนึ่ง menu/action catalog','code:text;parent_id:uuid?=platform.ui_features.id;permission_id:uuid?=security.permissions.id;kind:text;labels:jsonb','U(code)','labels th/lo/zh/my; menu ไม่ใช่ authorization',global_=True)
add('platform.feature_overrides','F','หนึ่งการเปิด/ปิด menu/action ที่ scope','feature_id:uuid=platform.ui_features.id;scope_id:uuid=security.access_scopes.id;enabled:boolean','U(company_id,feature_id,scope_id)','permission guard ยังตรวจแม้ menu hidden')
add('platform.audit_events','F','หนึ่งเหตุการณ์ตรวจสอบ','actor_id:uuid?=security.users.id;action:text;entity_kind:text;entity_id:uuid?;document_id:uuid?=platform.documents.id;before_data:jsonb?;after_data:jsonb?;reason:text?;request_id:uuid;ip:inet?;user_agent:text?;occurred_at:timestamptz','I(company_id,occurred_at); I(company_id,document_id,occurred_at)','entity_id เชิงหลักฐาน ไม่ใช่ FK ธุรกิจ; allowlist PII; เก็บ >=5 ปี ห้าม runtime update/delete',mode='append')
add('security.auth_events','F','หนึ่งเหตุการณ์ auth กลาง','user_id:uuid?=security.users.id;event_type:text;request_id:uuid;occurred_at:timestamptz;ip:inet?;reason_code:text?','I(user_id,occurred_at)','แยก audit tenant; ไม่ log password/token/email ที่ login ล้มเหลว',mode='append',global_=True)
# Master data
add('catalog.units','F','หนึ่งหน่วยในบริษัท','code:text;name:text;dimension:text;decimal_places:integer;active:boolean','U(company_id,code)','COUNT/MASS/VOLUME; dimension immutable หลังมีธุรกรรม')
add('catalog.categories','F','หนึ่งหมวดสินค้า','parent_id:uuid?=catalog.categories.id;code:text;name:text;active:boolean','U(company_id,code)','no cycle')
add('catalog.products','F','หนึ่งสินค้ากลาง','code:text;barcode:text?;name:text;description:text?;category_id:uuid?=catalog.categories.id;stock_unit_id:uuid=catalog.units.id;tracking_mode:text;price:numeric(20,6);cost:numeric(20,6)?;active:boolean;deleted_at:timestamptz?;lot_required:boolean;package_required:boolean;shelf_life_hours:integer?;picking_policy:text','U(company_id,code); I(company_id,barcode); I(company_id,deleted_at,created_at)','tracking QUANTITY/WEIGHT/DUAL; price/cost เป็น master reference ไม่ใช่ source of stock value')
add('catalog.product_units','P','หนึ่งหน่วยซื้อ/แพ็กของสินค้า','product_id:uuid=catalog.products.id;unit_id:uuid=catalog.units.id;code:text;conversion_mode:text;fixed_factor:numeric(24,9)?;order_precision:integer;valid_from:timestamptz;valid_to:timestamptz?','U(company_id,product_id,code,valid_from)','FIXED factor >0 และ dimension เทียบกันได้; VARIABLE_WEIGHT ไม่ใช้ factor แปลงแพ็กเป็น kg; document snapshot')
add('catalog.product_barcodes','W','หนึ่ง barcode สินค้า/หน่วยบรรจุ','product_id:uuid=catalog.products.id;product_unit_id:uuid?=catalog.product_units.id;code:text;active:boolean','U(company_id,code)','Product.barcode เป็น primary alias ที่ต้องตรงกับตารางนี้')
add('catalog.product_translations','F','หนึ่งคำแปลต่อสินค้า/ภาษา','product_id:uuid=catalog.products.id;locale:text;name:text;description:text?','U(company_id,product_id,locale)')
add('catalog.branch_products','P','หนึ่งนโยบายสินค้าต่อสาขา','product_id:uuid=catalog.products.id;branch_id:uuid=org.branches.id;active:boolean;min_stock:numeric(20,6)?;par_stock:numeric(20,6)?;shelf_life_hours:integer?','U(company_id,product_id,branch_id)','ไม่เก็บยอดคงเหลือใน master')
add('catalog.suppliers','P','หนึ่งผู้ขายในบริษัท','code:text;legal_name:text;tax_id:text?;kind:text;internal_branch_id:uuid?=org.branches.id;active:boolean;deleted_at:timestamptz?;payment_terms_days:integer;currency:char(3);notes:text?','U(company_id,code)','EXTERNAL/INTERNAL; internal ไม่แปลว่าต้องซื้อเสมอ ใช้ transfer ตามธุรกิจ')
add('catalog.supplier_contacts','P','หนึ่งผู้ติดต่อ supplier','supplier_id:uuid=catalog.suppliers.id;name:text;phone:text?;email:text?;channel:text?;active:boolean','I(company_id,supplier_id)')
add('catalog.supplier_addresses','P','หนึ่งที่อยู่ supplier','supplier_id:uuid=catalog.suppliers.id;kind:text;address_line1:text;address_line2:text?;province_id:uuid=geo.provinces.id;district_id:uuid=geo.districts.id;subdistrict_id:uuid=geo.subdistricts.id;postal_code_id:uuid=geo.postal_codes.id;tax_branch_code:text?;is_default:boolean','partial U(company_id,supplier_id,kind) WHERE is_default')
add('catalog.supplier_products','P','หนึ่งข้อเสนอสินค้า/หน่วยจาก supplier','supplier_id:uuid=catalog.suppliers.id;product_id:uuid=catalog.products.id;product_unit_id:uuid=catalog.product_units.id;supplier_sku:text?;minimum_order:numeric(20,6)?;lead_days:integer?;active:boolean','U(company_id,supplier_id,product_id,product_unit_id)','unit ต้องเป็นของ product เดียวกัน')
add('catalog.supplier_prices','P','หนึ่งราคาช่วงเวลาต่อข้อเสนอ','supplier_product_id:uuid=catalog.supplier_products.id;valid_from:timestamptz;valid_to:timestamptz?;unit_price:numeric(20,6);currency:char(3);tax_code:text;tax_rate:numeric(9,6);tax_inclusive:boolean;discount_percent:numeric(9,6)','I(company_id,supplier_product_id,valid_from); no overlapping active ranges','ราคาเปลี่ยนสร้างช่วงใหม่ ไม่แก้ snapshot PO')
add('catalog.branch_supplier_products','P','หนึ่งรายการที่สาขาซื้อได้','branch_id:uuid=org.branches.id;supplier_product_id:uuid=catalog.supplier_products.id;active:boolean','U(company_id,branch_id,supplier_product_id)')
# Purchasing: stable lines and revisions
add('purchasing.purchase_orders','P','หัว PO และตัวชี้รุ่นที่มีผล','document_id:uuid=platform.documents.id;supplier_id:uuid=catalog.suppliers.id;warehouse_id:uuid=org.warehouses.id;current_revision_no:integer;effective_revision_no:integer?;held:boolean;hold_reason:text?;legacy_number:text?','U(company_id,document_id); I(company_id,supplier_id)','FK current/effective -> revisions แบบ deferred; branch/supplier/warehouse immutable หลัง issue')
add('purchasing.po_lines','P','identity รายการ PO คงที่ข้ามรุ่น','document_line_id:uuid=platform.document_lines.id;po_id:uuid=purchasing.purchase_orders.id;product_id:uuid=catalog.products.id','U(company_id,document_line_id)','ห้ามใช้ line_no ใหม่ทับสินค้าเดิมที่มีส่งมอบ; remove ด้วย revision ไม่ลบ identity')
add('purchasing.po_revisions','P','หนึ่งรุ่น PO snapshot','po_id:uuid=purchasing.purchase_orders.id;revision_no:integer;state:text;currency:char(3);order_date:date;requested_delivery_date:date;buyer_snapshot:jsonb;supplier_snapshot:jsonb;shipping_snapshot:jsonb;terms_snapshot:jsonb;net_amount:numeric(20,2);tax_amount:numeric(20,2);gross_amount:numeric(20,2);reason:text?;content_hash:text;approval_request_id:uuid?=platform.approval_requests.id;issued_at:timestamptz?','U(company_id,po_id,revision_no)','issued content immutable; state lifecycle ต่างจาก delivery/warehouse status')
add('purchasing.po_revision_lines','P','หนึ่ง line snapshot ต่อ revision','revision_id:uuid=purchasing.po_revisions.id;po_line_id:uuid=purchasing.po_lines.id;supplier_product_id:uuid?=catalog.supplier_products.id;product_unit_id:uuid=catalog.product_units.id;ordered_qty:numeric(20,6);unit_price:numeric(20,6);discount_amount:numeric(20,2);tax_rate:numeric(9,6);tax_amount:numeric(20,2);net_amount:numeric(20,2);gross_amount:numeric(20,2);conversion_snapshot:jsonb;description_snapshot:text;removed:boolean','U(company_id,revision_id,po_line_id)','line.po_id=revision.po_id; qty >=accepted+closed; order dimension immutable once confirmed')
add('purchasing.po_charges','P','หนึ่งส่วนลด/ค่าใช้จ่ายท้าย revision','revision_id:uuid=purchasing.po_revisions.id;kind:text;amount:numeric(20,2);tax_rate:numeric(9,6);allocation_basis:text;allocation_snapshot:jsonb','I(company_id,revision_id)','DISCOUNT/FREIGHT/OTHER; rounding remainder deterministic รายบรรทัด')
add('purchasing.po_dispatches','P','หนึ่งความพยายามส่ง PO revision','revision_id:uuid=purchasing.po_revisions.id;channel:text;recipient_snapshot:jsonb;sent_by:uuid=security.users.id;sent_at:timestamptz?;acknowledged_at:timestamptz?;evidence_file_id:uuid?=platform.files.id;status:text','I(company_id,revision_id,created_at)','download ไม่ใช่ sent; ใบตอบรับเก็บหลักฐาน; payload ผู้รับ/รุ่น immutable เปลี่ยนได้เฉพาะสถานะการส่ง/ตอบรับพร้อม audit')
add('purchasing.delivery_schedules','P','หนึ่งนัดส่งต่อ PO line','po_line_id:uuid=purchasing.po_lines.id;promised_at:timestamptz;scheduled_order_qty:numeric(20,6);supersedes_id:uuid?=purchasing.delivery_schedules.id;reason:text?;supplier_confirmed:boolean','I(company_id,promised_at)','การแก้นัดไม่เปลี่ยน qty PO; เก็บนัดเดิม',mode='append')
add('purchasing.po_closures','P','หนึ่งปิด/เปิดค้างรายบรรทัด','po_line_id:uuid=purchasing.po_lines.id;document_id:uuid=platform.documents.id;action:text;order_qty:numeric(20,6);reopens_id:uuid?=purchasing.po_closures.id;approval_request_id:uuid=platform.approval_requests.id;reason:text','I(company_id,po_line_id)','qty>0; REOPEN อ้าง CLOSE เดิมและ sum <= original; approved only contributes',mode='append')
add('purchasing.po_line_progress','P','projection สำหรับล็อกยอดต่อ PO line','po_line_id:uuid=purchasing.po_lines.id;effective_order_qty:numeric(20,6);accepted_order_qty:numeric(20,6);closed_order_qty:numeric(20,6)','U(company_id,po_line_id)','rebuildable; ค้าง=ordered-accepted-closed >=0; lock ก่อน confirm/close/revise; ไม่เก็บ stock')
# Delivery facts and append acceptance ledger
add('delivery.confirmations','P','หนึ่งรอบส่งมอบหนึ่ง PO','document_id:uuid=platform.documents.id;po_id:uuid=purchasing.purchase_orders.id;po_revision_id:uuid=purchasing.po_revisions.id;supplier_delivery_no:text?;arrived_at:timestamptz;checked_by:uuid?=security.users.id;legacy_warehouse_state:text;note:text?','U(company_id,document_id); I(company_id,po_id,arrived_at)','UNKNOWN/ALREADY_STOCKED/NOT_STOCKED; duplicate slip warning ไม่ unique แบบตัดหลายใบที่ใช้เลขเดียวกันโดยไม่ตรวจ')
add('delivery.confirmation_lines','P','ข้อเท็จจริงหนึ่งสินค้าต่อรอบส่ง','document_line_id:uuid=platform.document_lines.id;confirmation_id:uuid=delivery.confirmations.id;po_revision_line_id:uuid=purchasing.po_revision_lines.id;stated_order_qty:numeric(20,6);observed_order_qty:numeric(20,6);document_weight_kg:numeric(20,6)?;document_unit_price:numeric(20,6)?;unit_snapshot:jsonb;observed_note:text?','U(company_id,document_line_id)','confirmed facts immutable; accepted/issues แยก ledger; observed excess เก็บได้แต่ยังไม่ accepted')
add('delivery.issues','P','หนึ่งปัญหา/ส่วนที่กันไว้ของรอบส่ง','confirmation_line_id:uuid=delivery.confirmation_lines.id;kind:text;affected_order_qty:numeric(20,6);status:text;assigned_to:uuid?=security.users.id;reason:text;evidence_file_id:uuid?=platform.files.id','I(company_id,status,created_at)','SHORT/EXCESS/DAMAGED/WRONG_ITEM/PRICE/UNIT; ไม่เพิ่ม qty โดยปิด issue เฉย ๆ')
add('delivery.acceptance_entries','P','หนึ่งรายการยืนยัน/ย้อนจำนวนที่ยอมรับ','confirmation_line_id:uuid=delivery.confirmation_lines.id;issue_id:uuid?=delivery.issues.id;action:text;order_qty:numeric(20,6);reverses_id:uuid?=delivery.acceptance_entries.id;confirmed_by:uuid=security.users.id;confirmed_at:timestamptz;reason:text?;settings_snapshot:jsonb','I(company_id,confirmation_line_id); U(company_id,id)','ACCEPT/REVERSE qty>0; ยอมรับสุทธิ <=observed ที่แก้ตรวจแล้ว; ไม่สร้าง stock; reverse ไม่เกิน unused downstream',mode='append')
add('delivery.issue_actions','P','หนึ่งการดำเนินการปัญหา','issue_id:uuid=delivery.issues.id;action:text;order_qty:numeric(20,6)?;acceptance_entry_id:uuid?=delivery.acceptance_entries.id;closure_id:uuid?=purchasing.po_closures.id;actor_id:uuid=security.users.id;note:text','I(company_id,issue_id)','ACCEPT_EXISTING/CLOSE_OUTSTANDING/REPLACEMENT/REJECT; replacement ใหม่สร้าง confirmation ใหม่',mode='append')
add('delivery.line_progress','P','projection ยอดพร้อมเข้าคลังต่อ confirmation line','confirmation_line_id:uuid=delivery.confirmation_lines.id;accepted_order_qty:numeric(20,6);warehouse_consumed_order_qty:numeric(20,6);terminal_order_qty:numeric(20,6)','U(company_id,confirmation_line_id)','ready=accepted-consumed-terminal >=0; ไม่รวม failed/issues; warehouse counters เริ่มศูนย์และไม่ใช่ stock')
add('delivery.terminal_resolutions','W','จำนวนที่ยืนยันแล้วแต่ยุติการเข้าคลัง','confirmation_line_id:uuid=delivery.confirmation_lines.id;document_id:uuid=platform.documents.id;order_qty:numeric(20,6);reason:text;approval_request_id:uuid=platform.approval_requests.id;reverses_id:uuid?=delivery.terminal_resolutions.id','I(company_id,confirmation_line_id)','ใช้กับสูญเสีย/ปฏิเสธหลังยืนยันและก่อน stock; ส่งผล claim แต่ไม่เปิด PO ใหม่อัตโนมัติ',mode='append')
# Hardware and receiving
add('devices.agents','W','หนึ่งเครื่อง Device Agent','branch_id:uuid=org.branches.id;name:text;credential_hash:text;credential_version:integer;active:boolean;last_heartbeat_at:timestamptz?','U(company_id,name)','secret เก็บ hash/secret reference ไม่ plaintext')
add('devices.devices','W','หนึ่งเครื่องชั่ง/เครื่องพิมพ์','agent_id:uuid=devices.agents.id;warehouse_id:uuid=org.warehouses.id;kind:text;serial_no:text;model:text;protocol:text;active:boolean;calibrated_at:timestamptz?','U(company_id,serial_no)','SCALE/PRINTER; scope branch ตรง agent')
add('devices.weighings','W','หนึ่ง stable measurement หรือ authorized manual reading','device_id:uuid?=devices.devices.id;agent_event_id:text?;source:text;gross_kg:numeric(20,6);tare_kg:numeric(20,6);net_kg:numeric(20,6);stable:boolean;observed_at:timestamptz;received_at:timestamptz;operator_id:uuid=security.users.id;manual_reason:text?;override_approval_request_id:uuid?=platform.approval_requests.id;raw_payload:jsonb?','partial U(company_id,device_id,agent_event_id) WHERE device_id IS NOT NULL','net=gross-tare >=0; stable required except explicit manual override; scope and replay/staleness checked',mode='append')
add('receiving.receipts','W','หนึ่งใบชั่งรับเข้าคลัง','document_id:uuid=platform.documents.id;warehouse_id:uuid=org.warehouses.id;confirmation_id:uuid=delivery.confirmations.id;received_at:timestamptz;posted_at:timestamptz?;settings_snapshot:jsonb','U(company_id,document_id)','warehouse branch ตรง confirmation/PO; ไม่สร้างตรงจาก PO ข้าม delivery gate')
add('receiving.receipt_lines','W','หนึ่งรายละเอียดชั่งรับสินค้า','document_line_id:uuid=platform.document_lines.id;receipt_id:uuid=receiving.receipts.id;confirmation_line_id:uuid=delivery.confirmation_lines.id;product_id:uuid=catalog.products.id;accepted_order_qty_used:numeric(20,6);stock_qty:numeric(20,6);net_weight_kg:numeric(20,6)?;price_basis:text;unit_price:numeric(20,6);net_amount:numeric(20,2);tax_amount:numeric(20,2);inventory_value:numeric(20,6);conversion_snapshot:jsonb;quality_status:text','U(company_id,document_line_id)','consume order units vs measured stock units independent; nonnegative; exact record final warehouse facts')
add('receiving.receipt_weighings','W','หนึ่ง measurement ที่ใช้ใน line','receipt_line_id:uuid=receiving.receipt_lines.id;weighing_id:uuid=devices.weighings.id','U(company_id,weighing_id)','ไม่ reuse measurement ใน receipt ใหม่; reversal เก็บ mapping เดิม')
add('receiving.receipt_lots','W','หนึ่งการแบ่ง line เข้า lot/package/location','receipt_line_id:uuid=receiving.receipt_lines.id;lot_id:uuid=inventory.lots.id;package_id:uuid?=inventory.packages.id;location_id:uuid=org.locations.id;stock_qty:numeric(20,6);weight_kg:numeric(20,6)?;inventory_value:numeric(20,6)','I(company_id,receipt_line_id)','sum splits = line quantities/value; receipt lot creation+posting atomic')
add('receiving.variances','W','หนึ่งข้อแตกต่างตอนชั่ง/รับจริง','receipt_line_id:uuid=receiving.receipt_lines.id;kind:text;expected_value:numeric(20,6)?;actual_value:numeric(20,6)?;unit_id:uuid?=catalog.units.id;reason:text;status:text;approval_request_id:uuid?=platform.approval_requests.id','I(company_id,status)','weight ต่างไม่แก้ delivery qty; เกิน threshold hold ก่อน post')
add('receiving.ocr_runs','W','หนึ่ง OCR attempt ของไฟล์','document_id:uuid=platform.documents.id;file_id:uuid=platform.files.id;provider:text;status:text;raw_extraction:jsonb?;confidence:jsonb?;confirmed_values:jsonb?;reviewed_by:uuid?=security.users.id;reviewed_at:timestamptz?','I(company_id,document_id)','raw ไม่ทับ confirmed; human review ก่อนใช้ post; handwriting manual')
# Shared inventory kernel
add('inventory.lots','W','หนึ่ง lot คุณภาพ/อายุเดียวกัน','product_id:uuid=catalog.products.id;lot_code:text;supplier_id:uuid?=catalog.suppliers.id;supplier_lot_code:text?;origin_document_line_id:uuid=platform.document_lines.id;manufactured_at:timestamptz?;expires_at:timestamptz?;received_at:timestamptz;origin_kind:text','U(company_id,lot_code); I(company_id,product_id,expires_at)','warehouse ไม่ติดกับ lot เพราะโอนได้; dates immutable หลัง post; nonlot product ใช้ internal lot เพื่อ kernel เดียว')
add('inventory.packages','W','หนึ่งหน่วยห่อ/ภาชนะที่ trace ได้','lot_id:uuid=inventory.lots.id;package_code:text;parent_package_id:uuid?=inventory.packages.id;initial_stock_qty:numeric(20,6);initial_weight_kg:numeric(20,6)?;expires_at:timestamptz?;status:text','U(company_id,package_code)','remaining มาจาก ledger ไม่แก้ initial; split/repack ผ่าน document+genealogy ไม่สร้าง stock ฟรี')
add('inventory.barcodes','W','หนึ่งรหัส lot หรือ package','code:text;lot_id:uuid?=inventory.lots.id;package_id:uuid?=inventory.packages.id;active:boolean','U(code)','exactly one target; global code opaque ไม่รวม PII; API ยังตรวจ tenant')
add('inventory.lot_genealogy','O','หนึ่งส่วนเชื่อม lot ต้นทาง/ผลลัพธ์','parent_lot_id:uuid=inventory.lots.id;child_lot_id:uuid=inventory.lots.id;document_id:uuid=platform.documents.id;kind:text;input_stock_qty:numeric(20,6);input_weight_kg:numeric(20,6)?;allocated_value:numeric(20,6)','U(company_id,parent_lot_id,child_lot_id,document_id)','RETURN/PROCESS/REPACK; DAG ไม่มีวงจร; multiple inputs/outputs supported',mode='append')
add('inventory.stock_accounts','W','หนึ่ง bucket ที่เป็น endpoint ของ ledger','product_id:uuid=catalog.products.id;lot_id:uuid?=inventory.lots.id;package_id:uuid?=inventory.packages.id;kind:text;location_id:uuid?=org.locations.id;custody_document_line_id:uuid?=platform.document_lines.id;stock_status:text','U NULLS NOT DISTINCT(company_id,product_id,lot_id,package_id,kind,location_id,custody_document_line_id,stock_status)','WAREHOUSE/TRANSIT/CUSTODY/EXTERNAL; warehouse ต้อง location+lot; transit/custody ต้อง doc line+lot; external ไม่ใช้ location; package lot/product consistency')
add('inventory.postings','W','หนึ่ง ledger posting ต่อ source action','document_id:uuid=platform.documents.id;action:text;posted_at:timestamptz;reverses_posting_id:uuid?=inventory.postings.id;request_id:uuid;created_by:uuid=security.users.id','U(company_id,document_id,action); U(company_id,reverses_posting_id)','immutable append; correction ใช้ document ใหม่และ inverse entries',mode='append')
add('inventory.ledger_entries','W','หนึ่ง signed delta ต่อ stock account','posting_id:uuid=inventory.postings.id;account_id:uuid=inventory.stock_accounts.id;document_line_id:uuid=platform.document_lines.id;stock_qty_delta:numeric(20,6);weight_kg_delta:numeric(20,6)?;value_delta:numeric(20,6);entry_no:integer','U(company_id,posting_id,entry_no); I(company_id,account_id,created_at)','product/unit ตาม account; immutable; zero qty allowed เฉพาะ cost adjustment; balanced contra entries',mode='append')
add('inventory.balances','W','projection ยอดปัจจุบันต่อ account','account_id:uuid=inventory.stock_accounts.id;stock_qty:numeric(20,6);weight_kg:numeric(20,6)?;inventory_value:numeric(20,6);last_entry_id:uuid?=inventory.ledger_entries.id','U(company_id,account_id)','WAREHOUSE/TRANSIT/CUSTODY nonnegative; EXTERNAL contra signed allowed; rebuild from ledger')
add('inventory.reservations','W','หนึ่งการกันยอดของ source line/account','document_line_id:uuid=platform.document_lines.id;account_id:uuid=inventory.stock_accounts.id;stock_qty:numeric(20,6);weight_kg:numeric(20,6)?;status:text;expires_at:timestamptz?','I(company_id,account_id,status); U(company_id,document_line_id,account_id)','HELD/CONSUMED/RELEASED/EXPIRED; available=balance-held; no double deduction')
add('inventory.cost_layers','W','หนึ่งต้นทุนรับเข้า/ผลผลิตของ lot','lot_id:uuid=inventory.lots.id;source_line_id:uuid=platform.document_lines.id;original_stock_qty:numeric(20,6);original_value:numeric(20,6);cost_method:text','U(company_id,source_line_id,lot_id)','proposed SPECIFIC_LOT basis; ราคาซื้อ/ภาษีที่ reclaim ได้ไม่ปนต้นทุน; decisions ระบุ')
add('inventory.cost_allocations','W','หนึ่งต้นทุนที่ออก/คืนจาก layer','layer_id:uuid=inventory.cost_layers.id;ledger_entry_id:uuid=inventory.ledger_entries.id;stock_qty:numeric(20,6);value:numeric(20,6);direction:text','U(company_id,layer_id,ledger_entry_id)','ISSUE/RESTORE; sum not over layer; return restore uses original issue cost',mode='append')
add('inventory.opening_lines','W','หนึ่งสต็อกตั้งต้นที่ยืนยัน','document_line_id:uuid=platform.document_lines.id;account_id:uuid=inventory.stock_accounts.id;stock_qty:numeric(20,6);weight_kg:numeric(20,6)?;inventory_value:numeric(20,6);import_row_id:uuid?=integration.import_rows.id','U(company_id,document_line_id)','approved opening doc; ไม่มี fake delivery/PO เพิ่มซ้ำ')
add('inventory.status_changes','W','หนึ่งการกักกัน/ปล่อย/เปลี่ยน bucket','document_line_id:uuid=platform.document_lines.id;from_account_id:uuid=inventory.stock_accounts.id;to_account_id:uuid=inventory.stock_accounts.id;stock_qty:numeric(20,6);weight_kg:numeric(20,6)?;reason:text;approval_request_id:uuid?=platform.approval_requests.id','U(company_id,document_line_id)','same product lot location; ledger pair; expired blocked by query even before scheduler')
add('inventory.cost_adjustment_lines','W','หนึ่งแก้ต้นทุนที่ไม่มีการเปลี่ยนจำนวน','document_line_id:uuid=platform.document_lines.id;account_id:uuid=inventory.stock_accounts.id;cost_layer_id:uuid=inventory.cost_layers.id;value_delta:numeric(20,6);reason:text;approval_request_id:uuid=platform.approval_requests.id','U(company_id,document_line_id)','qty delta0; remaining stock/cost variance ปันส่วนตาม policy; ไม่ rewrite receipt')
add('inventory.repack_lines','W','หนึ่งคู่แบ่ง/รวม package ของ lot เดิม','document_line_id:uuid=platform.document_lines.id;from_account_id:uuid=inventory.stock_accounts.id;to_account_id:uuid=inventory.stock_accounts.id;stock_qty:numeric(20,6);weight_kg:numeric(20,6)?;value:numeric(20,6)','U(company_id,document_line_id)','same product/lot; packages ต่างกันได้; qty/value conserved; package ancestry ต้องไม่มีวงจร')
# Operations
add('inventory.transfers','O','หนึ่งเอกสารย้ายภายในบริษัท','document_id:uuid=platform.documents.id;from_warehouse_id:uuid=org.warehouses.id;to_warehouse_id:uuid=org.warehouses.id;dispatched_at:timestamptz?;closed_at:timestamptz?;approval_request_id:uuid?=platform.approval_requests.id','U(company_id,document_id)','branch scope both ends; inter-company transfers excluded use separate purchase/sale contract')
add('inventory.transfer_lines','O','หนึ่ง line lot/package ที่ส่ง','document_line_id:uuid=platform.document_lines.id;transfer_id:uuid=inventory.transfers.id;from_account_id:uuid=inventory.stock_accounts.id;dispatched_qty:numeric(20,6);dispatched_weight_kg:numeric(20,6)?;transit_account_id:uuid=inventory.stock_accounts.id','U(company_id,document_line_id)','dispatch warehouse -> transit; no destination increase until receive')
add('inventory.transfer_receipts','O','หนึ่งรอบรับ transfer line','document_line_id:uuid=platform.document_lines.id;transfer_line_id:uuid=inventory.transfer_lines.id;to_account_id:uuid=inventory.stock_accounts.id;received_qty:numeric(20,6);received_weight_kg:numeric(20,6)?;variance_reason:text?','U(company_id,document_line_id)','receive transit->warehouse; shortage remains transit until approved resolution')
add('inventory.count_sessions','O','หนึ่งรอบตรวจนับ','document_id:uuid=platform.documents.id;warehouse_id:uuid=org.warehouses.id;scope_snapshot:jsonb;blind_count:boolean;started_at:timestamptz?;completed_at:timestamptz?;freeze_policy:text','U(company_id,document_id)','baseline scope freeze mandatory; no movements in frozen accounts until released')
add('inventory.count_scope_locks','O','หนึ่ง freeze ที่มีผลต่อ warehouse','warehouse_id:uuid=org.warehouses.id;session_id:uuid=inventory.count_sessions.id;active:boolean;released_at:timestamptz?','partial U(company_id,warehouse_id) WHERE active','baseline freeze ทั้งwarehouse แม้ count subset; postingและเปิด/ปิดfreezeล็อก warehouse row เดียวกัน')
add('inventory.count_lines','O','หนึ่ง account snapshot ในรอบนับ','document_line_id:uuid=platform.document_lines.id;session_id:uuid=inventory.count_sessions.id;account_id:uuid=inventory.stock_accounts.id;snapshot_qty:numeric(20,6);snapshot_weight_kg:numeric(20,6)?;snapshot_version:integer;counted_qty:numeric(20,6)?;counted_weight_kg:numeric(20,6)?;counted_by:uuid?=security.users.id;counted_at:timestamptz?;weighing_id:uuid?=devices.weighings.id','U(company_id,session_id,account_id); U(company_id,document_line_id)','unknown stock creates controlled zero snapshot line while freeze active; not loose text')
add('inventory.adjustment_lines','O','หนึ่งผลปรับยอดที่อนุมัติ','document_line_id:uuid=platform.document_lines.id;account_id:uuid=inventory.stock_accounts.id;count_line_id:uuid?=inventory.count_lines.id;before_qty:numeric(20,6);delta_qty:numeric(20,6);after_qty:numeric(20,6);delta_weight_kg:numeric(20,6)?;delta_value:numeric(20,6);reason:text;approval_request_id:uuid=platform.approval_requests.id','U(company_id,document_line_id); partial U(company_id,count_line_id) WHERE count_line_id IS NOT NULL','after=before+delta >=0; post version must match frozen snapshot or recount')
add('withdrawal.requests','O','หนึ่งคำขอเบิก','document_id:uuid=platform.documents.id;warehouse_id:uuid=org.warehouses.id;usage_point_id:uuid=org.usage_points.id;purpose:text;approval_request_id:uuid?=platform.approval_requests.id','U(company_id,document_id)','CONSUMPTION/PROCESSING; mobile creates, management approves')
add('withdrawal.request_lines','O','หนึ่งสินค้าที่ขอเบิก','document_line_id:uuid=platform.document_lines.id;request_id:uuid=withdrawal.requests.id;product_id:uuid=catalog.products.id;requested_qty:numeric(20,6);requested_weight_kg:numeric(20,6)?','U(company_id,document_line_id)','requested vs issued separate')
add('withdrawal.issue_lines','O','หนึ่งการจ่ายจาก lot/package/account','document_line_id:uuid=platform.document_lines.id;request_line_id:uuid=withdrawal.request_lines.id;source_account_id:uuid=inventory.stock_accounts.id;custody_account_id:uuid=inventory.stock_accounts.id;issued_qty:numeric(20,6);issued_weight_kg:numeric(20,6)?;weighing_id:uuid?=devices.weighings.id;fifo_override_reason:text?','U(company_id,document_line_id)','warehouse->custody once; choose FEFO locks; record system recommendation in document snapshot')
add('withdrawal.consumptions','O','หนึ่งปิดใช้จริงจาก custody','document_line_id:uuid=platform.document_lines.id;issue_line_id:uuid=withdrawal.issue_lines.id;consumed_qty:numeric(20,6);consumed_weight_kg:numeric(20,6)?;reason:text?','U(company_id,document_line_id)','custody->external; ไม่ตัด warehouse ซ้ำ; close issued=consumed+returned+processing assigned+waste+remaining')
add('inventory.return_lines','O','หนึ่งคืนจาก custody เข้า warehouse','document_line_id:uuid=platform.document_lines.id;issue_line_id:uuid=withdrawal.issue_lines.id;from_account_id:uuid=inventory.stock_accounts.id;to_account_id:uuid=inventory.stock_accounts.id;returned_qty:numeric(20,6);returned_weight_kg:numeric(20,6)?;weighing_id:uuid?=devices.weighings.id;new_expiry:timestamptz;reason:text','U(company_id,document_line_id)','child lot/package+genealogy; expiry <= min(original,return+24h); cost from issue; no return>custody')
add('processing.process_definitions','O','หนึ่งกระบวนการแปรรูป version','code:text;revision:integer;name:text;yield_basis_unit_id:uuid=catalog.units.id;standard_yield:numeric(9,6)?;min_yield:numeric(9,6)?;max_yield:numeric(9,6)?;active:boolean','U(company_id,code,revision)','no BOM planning; only process/yield criteria')
add('processing.jobs','O','หนึ่งใบงานแปรรูป','document_id:uuid=platform.documents.id;definition_id:uuid=processing.process_definitions.id;warehouse_id:uuid=org.warehouses.id;settings_snapshot:jsonb;started_at:timestamptz?;completed_at:timestamptz?;actual_yield:numeric(9,6)?;yield_basis_input:numeric(20,6)?;yield_basis_output:numeric(20,6)?;approval_request_id:uuid?=platform.approval_requests.id','U(company_id,document_id)','null standard ไม่เทียบ alert; output/input gross issued basis explicitly')
add('processing.inputs','O','หนึ่ง input lot/custody ของ job','document_line_id:uuid=platform.document_lines.id;job_id:uuid=processing.jobs.id;issue_line_id:uuid=withdrawal.issue_lines.id;custody_account_id:uuid=inventory.stock_accounts.id;input_qty:numeric(20,6);input_weight_kg:numeric(20,6)?;weighing_id:uuid?=devices.weighings.id;input_value:numeric(20,6)','U(company_id,document_line_id)','allocate from issue custody; not warehouse deduct again')
add('processing.outputs','O','หนึ่ง output lot/package ของ job','document_line_id:uuid=platform.document_lines.id;job_id:uuid=processing.jobs.id;product_id:uuid=catalog.products.id;lot_id:uuid=inventory.lots.id;package_id:uuid?=inventory.packages.id;to_account_id:uuid=inventory.stock_accounts.id;output_qty:numeric(20,6);output_weight_kg:numeric(20,6)?;weighing_id:uuid?=devices.weighings.id;allocated_value:numeric(20,6)','U(company_id,document_line_id)','multiple outputs; post cost allocation+genealogy+ledger together')
add('inventory.waste_lines','O','หนึ่งสูญเสีย/ทิ้งจาก account','document_line_id:uuid=platform.document_lines.id;account_id:uuid=inventory.stock_accounts.id;process_input_id:uuid?=processing.inputs.id;stock_qty:numeric(20,6);weight_kg:numeric(20,6)?;reason:text;approval_request_id:uuid=platform.approval_requests.id;weighing_id:uuid?=devices.weighings.id','U(company_id,document_line_id)','warehouse/custody/transit -> external disposal; real loss tracked; require reason/approval')
add('processing.input_dispositions','O','หนึ่งการจัดสรร input เป็นผลผลิต/เหลือ/สูญเสีย','input_id:uuid=processing.inputs.id;output_id:uuid?=processing.outputs.id;return_line_id:uuid?=inventory.return_lines.id;waste_line_id:uuid?=inventory.waste_lines.id;basis_qty:numeric(20,6);allocated_value:numeric(20,6)','I(company_id,input_id)','exactly one target; conserved mass within approved loss; no double consume for returns/waste')
# Claims, pricing, labels, platform jobs/integration
add('purchasing.claims','O','หนึ่งใบเคลม supplier','document_id:uuid=platform.documents.id;supplier_id:uuid=catalog.suppliers.id;reason:text;status:text;approval_request_id:uuid?=platform.approval_requests.id','U(company_id,document_id)','เปิดจาก delivery issue หรือ receipt variance; financial outcome ไม่ปรับ stock เอง')
add('purchasing.claim_lines','O','หนึ่งรายการเคลมมีต้นทางชัด','document_line_id:uuid=platform.document_lines.id;claim_id:uuid=purchasing.claims.id;delivery_issue_id:uuid?=delivery.issues.id;receipt_variance_id:uuid?=receiving.variances.id;claimed_order_qty:numeric(20,6)?;claimed_stock_qty:numeric(20,6)?;claimed_amount:numeric(20,2);currency:char(3)','U(company_id,document_line_id)','exactly one source; qty basis explicit ห้ามบวก order qty กับ kg')
add('purchasing.claim_settlements','O','หนึ่งผลตกลงเคลม','claim_line_id:uuid=purchasing.claim_lines.id;kind:text;amount:numeric(20,2)?;quantity:numeric(20,6)?;unit_id:uuid?=catalog.units.id;replacement_confirmation_line_id:uuid?=delivery.confirmation_lines.id;credit_note_file_id:uuid?=platform.files.id;external_reference:text?;reason:text','I(company_id,claim_line_id)','REFUND/CREDIT/REPLACEMENT/REJECTED; sum bounded; ไม่ใช่ AP/general ledger',mode='append')
add('purchasing.supplier_return_lines','O','หนึ่งส่งคืน supplier จากสต็อกจริง','document_line_id:uuid=platform.document_lines.id;claim_line_id:uuid=purchasing.claim_lines.id;source_account_id:uuid=inventory.stock_accounts.id;stock_qty:numeric(20,6);weight_kg:numeric(20,6)?;value:numeric(20,6)','U(company_id,document_line_id)','ต้องเป็นของรับเข้าสต็อกแล้ว; ก่อน warehouse receipt ใช้ rejection/terminal resolution ไม่มี stock deduction')
add('purchasing.price_observations','P','หนึ่งราคา snapshot ของ event ต้นทาง','source_line_id:uuid=platform.document_lines.id;source_stage:text;source_version:integer;product_id:uuid=catalog.products.id;supplier_id:uuid=catalog.suppliers.id;observed_at:timestamptz;quantity:numeric(20,6);unit_id:uuid=catalog.units.id;unit_price:numeric(20,6);currency:char(3);net_amount:numeric(20,2);tax_basis:text;normalized_unit_price:numeric(20,6)?;normalized_unit_id:uuid?=catalog.units.id;supersedes_id:uuid?=purchasing.price_observations.id;observation_kind:text;reverses_id:uuid?=purchasing.price_observations.id','U(company_id,source_line_id,source_stage,source_version); I(company_id,product_id,supplier_id,observed_at)','PO/DELIVERY/WAREHOUSE streams ไม่ปนกัน; OBSERVE/VOID; supersedes เป็น snapshot รุ่นใหม่ ไม่รวมทุกรุ่นซ้ำ; source line registry prevents orphan',mode='append')
add('devices.label_templates','W','หนึ่งรุ่นฉลาก','code:text;revision:integer;locale:text;width_mm:numeric(10,3);height_mm:numeric(10,3);template:jsonb;active:boolean','U(company_id,code,revision,locale)')
add('devices.print_jobs','W','หนึ่งงานพิมพ์/reprint','template_id:uuid=devices.label_templates.id;printer_id:uuid=devices.devices.id;package_id:uuid?=inventory.packages.id;lot_id:uuid?=inventory.lots.id;payload_snapshot:jsonb;requested_by:uuid=security.users.id;status:text;reprint_of_id:uuid?=devices.print_jobs.id;reprint_reason:text?','I(company_id,status,created_at)','exactly one package/lot target; reason required for reprint; retry same job not new barcode')
add('devices.print_attempts','W','หนึ่ง callback/attempt ของงานพิมพ์','print_job_id:uuid=devices.print_jobs.id;attempt_no:integer;agent_event_id:text;status:text;error_code:text?;acknowledged_at:timestamptz?','U(company_id,print_job_id,attempt_no); U(company_id,agent_event_id)','unknown result ไม่ auto print ซ้ำไม่จำกัด; print failure ไม่ rollback stock',mode='append')
add('integration.connections','F','หนึ่งการเชื่อมระบบภายนอก','code:text;provider:text;secret_ref:text;active:boolean;config:jsonb','U(company_id,code)','ไม่ใส่ secrets ใน config; ERP optional ไม่เป็น owner Master')
add('integration.external_mappings','P','หนึ่งรหัสต้นทางกับ internal entity','connection_id:uuid=integration.connections.id;entity_kind:text;external_id:text;internal_id:uuid;source_version:text?;last_synced_at:timestamptz?','U(company_id,connection_id,entity_kind,external_id)','polymorphic mapping validate via allowlisted adapter; internal_id ไม่ใช้เป็น business FK')
add('integration.import_batches','P','หนึ่งชุดนำเข้า','document_id:uuid?=platform.documents.id;source_file_id:uuid=platform.files.id;kind:text;status:text;cutoff_at:timestamptz;checksum:text;validated_by:uuid?=security.users.id;summary:jsonb','U(company_id,kind,checksum)','dry-run/validate ก่อน commit; PO/delivery and stock opening คนละ batch')
add('integration.import_rows','P','หนึ่งแถว staging','batch_id:uuid=integration.import_batches.id;row_no:integer;external_key:text;payload:jsonb;errors:jsonb?;status:text;target_kind:text?;target_id:uuid?','U(company_id,batch_id,row_no); I(company_id,batch_id,status)','payload untrusted; target registry resolver allowlist; not source of operational totals')
add('integration.idempotency_keys','F','หนึ่ง command request fingerprint','actor_id:uuid=security.users.id;operation:text;key:text;payload_hash:text;status:text;result_document_id:uuid?=platform.documents.id;response_snapshot:jsonb?;lease_until:timestamptz?;expires_at:timestamptz','U(company_id,actor_id,operation,key)','bootstrap company idempotency แยก global table; no token response persisted')
add('security.provision_requests','F','หนึ่ง global request สร้างบริษัท','actor_id:uuid=security.users.id;idempotency_key:text;payload_hash:text;result_company_id:uuid?=org.companies.id;status:text;expires_at:timestamptz','U(actor_id,idempotency_key)','จำเป็นก่อนมี company_id; explicit provision permission',global_=True)
add('integration.outbox_events','F','หนึ่ง durable integration event/job intent','event_id:uuid;event_name:text;schema_version:integer;aggregate_kind:text;aggregate_id:uuid;aggregate_version:integer;correlation_id:uuid;occurred_at:timestamptz;payload:jsonb;status:text;attempts:integer;next_attempt_at:timestamptz;lease_until:timestamptz?;sent_at:timestamptz?;last_error_code:text?','U(event_id); partial I(next_attempt_at) WHERE status IN (PENDING,RETRY)','payload schema checked; persisted with business commit; transport metadata mutable, event identity/payload immutable')
add('integration.inbox_events','F','หนึ่ง event ต่อ consumer','consumer_name:text;event_id:uuid;payload_hash:text;processed_at:timestamptz;result_reference:jsonb?','U(company_id,consumer_name,event_id)','insert+consumer effect same transaction; failed processing rolls back row',mode='append')
add('integration.deliveries','R','หนึ่งความพยายามส่งออก ERP/บัญชี','connection_id:uuid=integration.connections.id;outbox_event_id:uuid=integration.outbox_events.id;document_id:uuid=platform.documents.id;status:text;attempts:integer;external_reference:text?;request_hash:text;last_error_code:text?;next_attempt_at:timestamptz?','U(company_id,connection_id,outbox_event_id)','no direct ERP DB write; retry idempotent;ไม่ถือ HTTP202 ว่า provider accepted accounting completed')
add('notification.rules','R','หนึ่งกฎแจ้งเตือนต่อ scope','code:text;scope_id:uuid=security.access_scopes.id;event_type:text;config:jsonb;active:boolean','U(company_id,scope_id,code)','PO overdue/low stock/expiry/yield/claim/integration error')
add('notification.notifications','R','หนึ่งข้อความต่อ user/event','recipient_id:uuid=security.users.id;outbox_event_id:uuid?=integration.outbox_events.id;rule_id:uuid?=notification.rules.id;dedupe_key:text;locale:text;title:text;body:text;document_id:uuid?=platform.documents.id;read_at:timestamptz?','U(company_id,recipient_id,dedupe_key)','ตรวจสิทธิ์ก่อนแสดง/deep link; no sensitive payload in public push')
add('notification.attempts','R','หนึ่งการส่ง notification ผ่าน channel','notification_id:uuid=notification.notifications.id;channel:text;attempt_no:integer;status:text;provider_message_id:text?;error_code:text?;sent_at:timestamptz?','U(company_id,notification_id,channel,attempt_no)','retry/retention; append outcomes',mode='append')
add('reporting.export_jobs','R','หนึ่ง export ตามสิทธิ์ ณ เวลาขอ','requested_by:uuid=security.users.id;report_code:text;filters:jsonb;authorized_scope_snapshot:jsonb;status:text;as_of:timestamptz?;output_file_id:uuid?=platform.files.id;expires_at:timestamptz;error_code:text?','I(company_id,requested_by,created_at)','ตรวจสิทธิ์ซ้ำตอนทำ/ดาวน์โหลด ไม่เชื่อ snapshot เป็น authority ถาวร')
add('reporting.refresh_runs','R','หนึ่ง aggregate refresh','view_name:text;started_at:timestamptz;finished_at:timestamptz?;watermark:timestamptz?;status:text;error_code:text?','I(company_id,view_name,started_at)','allowlisted view ไม่ dynamic SQL user input; dashboard freshness')
# Validate all internal references and write deterministic docs.
by={t['name']:t for t in T}
assert len(by)==len(T)
for t in T:
    assert len({c['name'] for c in t['columns']})==len(t['columns']),t['name']
    for c in t['columns']:
        if c['reference']:
            table,col=c['reference'].rsplit('.',1)
            assert table in by,(t['name'],c)
            assert col in {x['name'] for x in by[table]['columns']},(t['name'],c)
from thai_comments import annotate
annotate(T)
(ROOT/'model.catalog.json').write_text(json.dumps({'status':'DESIGN_ONLY_NOT_MIGRATION','tables':T},ensure_ascii=False,indent=2)+'\n')
lines=['# พจนานุกรมข้อมูล HOTPOTMAN ทั้งระบบ','','สถานะ: แบบออกแบบ ยังไม่ได้สร้างฐานข้อมูลหรือรัน Migration','',f'รวม {len(T)} ตารางเชิงตรรกะ แบ่งสร้างตามเฟส ไม่ใช่ข้อกำหนดให้สร้างทั้งหมดในวันแรก','',
'## วิธีอ่าน','','- `F` Foundation, `P` Purchasing/Delivery Phase 1, `W` Weighing/Warehouse, `O` Operations, `R` Reporting/Integration delivery; ดูแผนใน 04-migration-and-acceptance.md',
'- ทุกตารางมี `id uuid PK`; tenant table มี `company_id` และต้องมี `UNIQUE(company_id,id)` เพื่อใช้ composite FK กฎนี้รวมตาราง join ที่มี surrogate id',
'- `U` unique, `I` index; reference คอลัมน์แสดง FK target เชิงตรรกะ ใน implementation ต้องขยาย company_id ตามกฎ composite FK ใน 03-invariants-and-transactions.md',
'- เว้นแต่ระบุ `?`/nullable ในตาราง คอลัมน์เป็น NOT NULL; default id=UUID, created_at/updated_at=now(), version=1; ค่าอื่นต้องส่ง explicit หรือค่าที่ระบุใน policy ไม่เดา default',
'- Append table ไม่มี updated_at/version; ห้าม runtime update/delete business content ใช้ reversal ใหม่ ส่วน state-machine/projection เป็น mutable ตามกฎ',
'- JSON ใช้ snapshot/config/payload ที่ validate schema และ version ไม่ใช้แทน FK/จำนวน/เงินหลัก; address/locale text เป็นข้อมูลธุรกิจ ไม่ใช่คำสั่ง',
'- UUID ไม่รับประกัน tenant isolation; actor FK global user ต้องตรวจ membership ณ เวลา action และเก็บ audit เมื่อสิทธิ์เปลี่ยนภายหลัง',
'- FK ปริยาย `ON DELETE RESTRICT`; ไม่มี cascade ลบประวัติ เอกสาร immutable ตอน confirm/post แม้ระบุ mutable สำหรับ draft/state',
'- Field status/kind ใช้ text + CHECK allowlist ตาม 03; ไม่เปิดรับค่าอิสระจาก client',
'']
for t in T:
    lines += [f"## `{t['name']}`",'',f"**เฟส:** {t['phase']} · **หนึ่งแถวคือ:** {t['grain']} · **ประเภท:** {t['mode']}",'', f"**คำอธิบาย:** {t['comment_th']}", '', '| คอลัมน์ | PostgreSQL type | NULL | PK / FK | อ้างอิง | คำอธิบายภาษาไทย |','|---|---|---|---|---|---|']
    for c in t['columns']:
        lines += [f"| `{c['name']}` | `{c['type']}` | {'ได้' if c['nullable'] else 'ไม่ได้'} | {c['key_role']} | {('`'+c['reference']+'`') if c['reference'] else '—'} | {c['comment_th']} |"]
    lines += ['',f"**Keys / Index:** {t['keys'] or 'PK และ tenant FK ตามกฎกลาง'}",'',f"**กฎเฉพาะ:** {t['rules'] or 'ใช้กฎ tenant, FK และ audit กลาง'}",'']
(ROOT/'02-data-dictionary.md').write_text('\n'.join(lines).rstrip()+'\n')
print(f'{len(T)} tables; {sum(len(t["columns"]) for t in T)} columns; all FK references resolved')
